global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # Evaluate rules every 15 seconds.

# Alertmanager Configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#       # docker
#       - targets: ['host.docker.internal:9093']
#       # Ubuntu Installation manually
#       # - targets: ['192.168.64.2:9093']


scrape_configs:

- job_name: 'prometheus'
  scrape_interval: 15s
  metrics_path: /metrics
  static_configs:
    # - targets: ['host.docker.internal:9090']
    - targets: ['prometheus:9090']

- job_name: 'pushgateway'
  scrape_interval: 15s
  honor_labels: true
  static_configs:
    # - targets: ['host.docker.internal:9091']
    - targets: ['pushgateway:9091']
   
    
